import type { Metadata } from 'next';
import classNames from 'classnames';
import { Roboto_Condensed } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import Footer from '@/layout/Footer';
import Header from '@/layout/Header';

const roboto = Roboto_Condensed({
  subsets: ['cyrillic', 'latin'],
  weight: '700',
  display: 'swap',
  variable: '--font-roboto',
});

const geologica = localFont({
  src: [
    {
      path: '../../../public/fonts/Geologica-ExtraLight.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-geologica',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const slides = [
  { id: 1, content: 'slide' },
  { id: 2, content: 'slide' },
  { id: 3, content: 'slide' },
  { id: 4, content: 'slide' },
  { id: 5, content: 'slide' },
  { id: 6, content: 'slide' },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={classNames(
          geologica.variable,
          roboto.variable,
          'h-full min-h-screen'
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
