import type { Metadata } from 'next';
import classNames from 'classnames';
import { Roboto_Condensed } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import ProductSwiper from '@/components/common/Swiper/ProductSwiper';
const roboto = Roboto_Condensed({
  subsets: ['cyrillic', 'latin'],
  weight: '700',
  display: 'swap',
  variable: '--font-roboto',
});

const geologica = localFont({
  src: [
    {
      path: '../../../public/fonts/Geologica-ExtraLight.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-geologica',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={classNames(
          geologica.variable,
          roboto.variable,
          'h-full min-h-screen'
        )}
      >
        {children}
        <div className="w-[400px] mx-[auto]">
          <ProductSwiper />
        </div>
      </body>
    </html>
  );
}
