import type { Metadata } from 'next';
import classNames from 'classnames';
import { Roboto_Condensed } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import Footer from '@/layout/Footer';
import Header from '@/layout/Header';

import ScrollLink from '@/components/ui/ScrollLink';
import Button from '@/components/ui/Button';
import OpenModalExampleBtn from '@/components/common/Modal/OpenModalExampleBtn';

const roboto = Roboto_Condensed({
  subsets: ['cyrillic', 'latin'],
  weight: '700',
  display: 'swap',
  variable: '--font-roboto',
});

const geologica = localFont({
  src: [
    {
      path: '../../../public/fonts/Geologica-ExtraLight.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Geologica-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-geologica',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={classNames(
          geologica.variable,
          roboto.variable,
          'h-full min-h-screen'
        )}
      >
        <Header />
        {children}
        <Footer />

        {/* Examples */}
        <div className="container text-center">ScrollLink</div>
        <div className="container py-2 flex flex-wrap gap-2 items-center bg-gray-400">
          <ScrollLink label="Primary" href="#sectionId" variant="primary" />
          <ScrollLink label="Secondary" href="#sectionId" variant="secondary" />
          <ScrollLink label="Navlink" href="#sectionId" variant="navlink" />
          <ScrollLink
            label="Primary2-Nav-To-Page"
            href="policy"
            variant="primary2"
          />
          <ScrollLink label="Policy" href="" variant="policy" />
        </div>
        <div className="container text-center">Button</div>
        <div className="container py-2 flex flex-wrap gap-2 items-center bg-gray-400">
          <Button label="ReadMore" variant="readmore" />
          <Button label="Primary" variant="primary" />
        </div>
        <div className="container text-center">Modals</div>
        <div className="container py-2 flex flex-wrap gap-2 items-center bg-gray-400">
          <OpenModalExampleBtn />
        </div>
      </body>
    </html>
  );
}
